// Public renderer projection captured from createFinalAssessmentTemplate via publicQuestionnaire.
// Test-only: production must use its pinned remote questionnaire. No scoring points or bands.
export function assessmentQuestionnaireFixture() {
  return {"formatVersion":2,"profile":"NIQ_FINAL_ASSESSMENT","sections":[
{"id":"disease_status","title":"Disease status","description":"Cancer diagnosis scoring inputs.","fields":[{"id":"tumour_type","label":"Type of tumour","type":"multi_select","help":"","unit":"","options":[{"id":"tumour_type_solid","label":"Solid Tumour","help":""},
{"id":"tumour_type_haematological","label":"Haematological","help":""},
{"id":"tumour_type_metastatic_secondary","label":"Metastatic / Secondary","help":""},
{"id":"tumour_type_in_situ","label":"In Situ","help":""}],"dependencies":[]},
{"id":"stage","label":"Stage","type":"select","help":"","unit":"","options":[{"id":"stage_localized","label":"Localized (stage 1–2)","help":""},
{"id":"stage_locally_advanced","label":"Locally Advanced (stage 3)","help":""},
{"id":"stage_metastatic","label":"Metastatic (Stage 4)","help":""}],"dependencies":[]},
{"id":"relapse_status","label":"Relapse status","type":"select","help":"","unit":"","options":[{"id":"relapse_status_first_diagnosis","label":"First Diagnosis","help":""},
{"id":"relapse_status_relapsed","label":"Relapsed","help":""},
{"id":"relapse_status_refractory","label":"Refractory","help":""}],"dependencies":[]}]},
{"id":"treatment","title":"Treatment","description":"Treatment and medication scoring inputs.","fields":[{"id":"treatment_status","label":"Treatment status","type":"conditional","help":"","unit":"","options":[{"id":"treatment_status_newly_diagnosed","label":"Newly Diagnosed","help":""},
{"id":"treatment_status_under_treatment","label":"Under Treatment","help":""},
{"id":"treatment_status_post_treatment","label":"Post-Treatment","help":""},
{"id":"treatment_status_palliative_care","label":"Palliative Care","help":""}],"dependencies":["palliative_status","palliative_timing"]},
{"id":"cancer_surgical_status","label":"Cancer surgical status","type":"select","help":"","unit":"","options":[{"id":"cancer_surgical_status_done","label":"Surgery Done","help":""},
{"id":"cancer_surgical_status_planned","label":"Planned","help":""},
{"id":"cancer_surgical_status_not_required","label":"Not Required","help":""},
{"id":"cancer_surgical_status_not_fit","label":"Not Fit for Surgery","help":""}],"dependencies":[]},
{"id":"current_cancer_treatment","label":"Current cancer treatment","type":"multi_select","help":"","unit":"","options":[{"id":"current_cancer_treatment_chemotherapy","label":"Chemotherapy (Cytotoxic)","help":""},
{"id":"current_cancer_treatment_immunotherapy","label":"Immunotherapy","help":""},
{"id":"current_cancer_treatment_radiation","label":"Radiation Therapy","help":""},
{"id":"current_cancer_treatment_targeted","label":"Targeted Therapy","help":""},
{"id":"current_cancer_treatment_hormonal","label":"Hormonal Therapy","help":""},
{"id":"current_cancer_treatment_other","label":"Other treatment","help":""}],"dependencies":[]},
{"id":"current_medications","label":"Current medications","type":"multi_select","help":"","unit":"","options":[{"id":"current_medications_blood_thinners","label":"Blood Thinners","help":""},
{"id":"current_medications_anti_hypertensives","label":"Anti-hypertensives (BP meds)","help":""},
{"id":"current_medications_anti_diabetics","label":"Anti-diabetics","help":""},
{"id":"current_medications_thyroid","label":"Thyroid","help":""},
{"id":"current_medications_cholesterols","label":"Cholesterols","help":""},
{"id":"current_medications_steroids","label":"Steroids","help":""},
{"id":"current_medications_anti_histamines","label":"Anti-histamines","help":""},
{"id":"current_medications_pain_medications","label":"Pain medications","help":""},
{"id":"current_medications_antibiotics","label":"Antibiotics","help":""},
{"id":"current_medications_antacid","label":"Antacid","help":""}],"dependencies":[]},
{"id":"supplements_intake","label":"Supplements intake","type":"multi_select","help":"","unit":"","options":[{"id":"supplements_intake_protein","label":"Protein supplements","help":""},
{"id":"supplements_intake_iron","label":"Iron","help":""},
{"id":"supplements_intake_calcium","label":"Calcium","help":""},
{"id":"supplements_intake_folic_acid","label":"Folic Acid","help":""},
{"id":"supplements_intake_multivitamins","label":"Multivitamins","help":""},
{"id":"supplements_intake_omega_3","label":"Omega-3","help":""}],"dependencies":[]}]},
{"id":"health_history","title":"Health history","description":"Co-morbidity, surgery count and family history scoring inputs.","fields":[{"id":"co_morbidities","label":"Co-morbidities","type":"multi_select","help":"","unit":"","options":[{"id":"co_morbidities_diabetes","label":"Diabetes","help":""},
{"id":"co_morbidities_hypertension","label":"Hypertension","help":""},
{"id":"co_morbidities_thyroid_disorder","label":"Thyroid Disorder","help":""},
{"id":"co_morbidities_kidney_disease","label":"Kidney Disease","help":""},
{"id":"co_morbidities_liver_disease","label":"Liver Disease","help":""},
{"id":"co_morbidities_cardiac_disease","label":"Cardiac Disease","help":""},
{"id":"co_morbidities_high_cholesterol","label":"High Cholesterol","help":""},
{"id":"co_morbidities_psychological_disorders","label":"Psychological Disorders","help":""}],"dependencies":[]},
{"id":"previous_surgeries","label":"Previous surgeries","type":"count","help":"Number of previous surgeries is multiplied by the configured point rate.","unit":"","options":[{"id":"previous_surgeries_yes","label":"Yes","help":""},
{"id":"previous_surgeries_no","label":"No","help":""}],"dependencies":["previous_surgery_count"]},
{"id":"family_history_cancer","label":"Family history of cancer","type":"yes_no","help":"","unit":"","options":[{"id":"family_history_cancer_yes","label":"Yes","help":""},
{"id":"family_history_cancer_no","label":"No","help":""}],"dependencies":[]}]},
{"id":"clinical_gut_health","title":"Clinical & GUT health","description":"Appetite and gastrointestinal symptom scoring inputs.","fields":[{"id":"appetite_status","label":"Appetite status","type":"select","help":"","unit":"","options":[{"id":"appetite_status_normal","label":"Normal","help":""},
{"id":"appetite_status_reduced","label":"Reduced","help":""},
{"id":"appetite_status_no_appetite","label":"No Appetite","help":""}],"dependencies":[]},
{"id":"gastrointestinal_symptoms","label":"Gastrointestinal symptoms","type":"multi_select","help":"","unit":"","options":[{"id":"gastrointestinal_symptoms_bloating","label":"Bloating","help":""},
{"id":"gastrointestinal_symptoms_acidity_reflux","label":"Acidity / Reflux","help":""},
{"id":"gastrointestinal_symptoms_nausea","label":"Nausea","help":""},
{"id":"gastrointestinal_symptoms_vomiting","label":"Vomiting","help":""},
{"id":"gastrointestinal_symptoms_early_satiety","label":"Early Satiety","help":""},
{"id":"gastrointestinal_symptoms_taste_changes","label":"Taste Changes (Dysgeusia)","help":""},
{"id":"gastrointestinal_symptoms_dysphagia","label":"Dysphagia","help":""},
{"id":"gastrointestinal_symptoms_pain_while_eating","label":"Pain while eating","help":""},
{"id":"gastrointestinal_symptoms_mouth_ulcers","label":"Mouth Ulcers / Mucositis","help":""}],"dependencies":[]}]},
{"id":"dietary_details","title":"Dietary details","description":"Weight, symptoms, function, stress, protein and fluids.","fields":[{"id":"weight_loss","label":"Weight loss/gain","type":"calculated","help":"Calculated from current weight and weight 1–2 months ago. The unrounded percentage determines the band.","unit":"","options":[],"dependencies":["previous_weight_kg","current_weight_kg"]},
{"id":"dietary_symptoms","label":"Symptoms","type":"multi_select","help":"","unit":"","options":[{"id":"dietary_symptoms_no_problem","label":"No problem while eating","help":""},
{"id":"dietary_symptoms_no_appetite","label":"No appetite, just did not feel like eating","help":""},
{"id":"dietary_symptoms_nausea","label":"Nausea","help":""},
{"id":"dietary_symptoms_vomiting","label":"Vomiting","help":""},
{"id":"dietary_symptoms_constipation","label":"Constipation","help":""},
{"id":"dietary_symptoms_diarrhoea","label":"Diarrhoea","help":""},
{"id":"dietary_symptoms_mouth_sores","label":"Mouth sores","help":""},
{"id":"dietary_symptoms_dry_mouth","label":"Dry mouth","help":""},
{"id":"dietary_symptoms_taste_funny","label":"Things taste funny or have no taste","help":""},
{"id":"dietary_symptoms_smells_bother","label":"Smells bother me","help":""},
{"id":"dietary_symptoms_swallowing_problems","label":"Problems while swallowing","help":""},
{"id":"dietary_symptoms_feel_full_quickly","label":"Feel full quickly","help":""},
{"id":"dietary_symptoms_fatigue","label":"Fatigue","help":""},
{"id":"dietary_symptoms_muscle_loss","label":"Muscle loss","help":""}],"dependencies":[]},
{"id":"functional_capacity","label":"Functional capacity","type":"select","help":"","unit":"","options":[{"id":"functional_capacity_normal_activity","label":"Normal Activity","help":""},
{"id":"functional_capacity_reduced_activity","label":"Reduced Activity","help":""},
{"id":"functional_capacity_bedridden","label":"Bedridden","help":""}],"dependencies":[]},
{"id":"stress_level","label":"Stress level","type":"select","help":"","unit":"","options":[{"id":"stress_level_high","label":"High","help":""},
{"id":"stress_level_moderate","label":"Moderate","help":""},
{"id":"stress_level_none_low","label":"None / Low","help":""}],"dependencies":[]},
{"id":"protein_intake","label":"Protein intake","type":"derived","help":"Derived from dietary intake. Normal intake and More than usual are Adequate.","unit":"","options":[],"dependencies":["dietary_intake"]},
{"id":"fluid_intake","label":"Fluid intake","type":"select","help":"","unit":"","options":[{"id":"fluid_intake_below_1_litre","label":"<1 litre","help":""},
{"id":"fluid_intake_one_to_two_litres","label":"1–2 litres","help":""},
{"id":"fluid_intake_above_2_litres","label":">2 litres","help":""}],"dependencies":[]}]}],
"supportingInputs":[
{"id":"palliative_status","label":"Palliative treatment path","kind":"select","required":false,"options":[{"id":"with_cancer","label":"With Cancer any stage","help":""},
{"id":"post_treatment","label":"Post treatment","help":""}]},
{"id":"palliative_timing","label":"Palliative post-treatment timing","kind":"select","required":false,"options":[{"id":"within_6_months","label":"Within 6 months","help":""},
{"id":"within_12_months","label":"Within 12 months","help":""},
{"id":"post_12_months","label":"Post 12 months","help":""}]},
{"id":"previous_surgery_count","label":"Number of previous surgeries","kind":"number","unit":"surgeries","required":false},
{"id":"previous_weight_kg","label":"Weight 1–2 months ago","kind":"number","unit":"kg","required":false},
{"id":"current_weight_kg","label":"Current weight","kind":"number","unit":"kg","required":false},
{"id":"dietary_intake","label":"Dietary intake change","kind":"select","required":false,"options":[{"id":"dietary_intake_normal","label":"Normal Intake","help":""},
{"id":"dietary_intake_more_than_usual","label":"More than usual","help":""},
{"id":"dietary_intake_reduced","label":"Reduced Intake / less than usual","help":""},
{"id":"dietary_intake_liquid","label":"Liquid Diet","help":""},
{"id":"dietary_intake_little_solid","label":"Little solid food","help":""},
{"id":"dietary_intake_tube_feeding","label":"Tube Feeding","help":""}]}]};
}
