import {
  boolean,
  check,
  date,
  customType,
  foreignKey,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  varchar,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

const encryptedBytes = customType<{ data: Uint8Array }>({
  dataType() {
    return "bytea";
  },
});

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
};

// Entity IDs are generated by the application before insert. Database defaults
// are intentionally absent so every creation path crosses that boundary.
const entityId = (name: string) => varchar(name, { length: 26 });

export const organizationStatus = pgEnum("organization_status", ["ACTIVE", "SUSPENDED", "CLOSED"]);
export const facilityStatus = pgEnum("facility_status", ["ACTIVE", "INACTIVE"]);
export const userStatus = pgEnum("user_status", ["INVITED", "ACTIVE", "SUSPENDED", "DEACTIVATED"]);
export const platformRole = pgEnum("platform_role", ["USER", "NIQ_ADMIN"]);
export const membershipRole = pgEnum("membership_role", ["ORGANIZATION_ADMIN", "MEDICAL", "SUPPORT"]);
export const invitationStatus = pgEnum("invitation_status", ["PENDING", "ACCEPTED", "EXPIRED", "REVOKED"]);
export const patientSex = pgEnum("patient_sex", ["FEMALE", "MALE", "OTHER", "UNKNOWN"]);
export const assessmentStatus = pgEnum("assessment_status", [
  "DRAFT",
  "READY_FOR_SCORING",
  "SCORING_PENDING",
  "SCORING_UNAVAILABLE",
  "SCORED",
  "UNDER_REVIEW",
  "COMPLETED",
  "VOIDED",
]);
export const measurementProvenance = pgEnum("measurement_provenance", [
  "AUTO_FACE_SCAN",
  "AUTOMATED_MANUAL_FALLBACK",
]);
export const scanStatus = pgEnum("scan_status", ["REQUESTED", "IN_PROGRESS", "SUCCEEDED", "FAILED", "UNAVAILABLE"]);
export const scoringRequestStatus = pgEnum("scoring_request_status", ["PENDING", "SUCCEEDED", "FAILED", "UNAVAILABLE"]);

export const organizations = pgTable(
  "organizations",
  {
    id: entityId("id").primaryKey(),
    legalName: text("legal_name").notNull(),
    displayName: text("display_name").notNull(),
    slug: text("slug").notNull(),
    status: organizationStatus("status").notNull().default("ACTIVE"),
    logoObjectKey: text("logo_object_key"),
    primaryColor: text("primary_color").notNull().default("#175CD3"),
    secondaryColor: text("secondary_color").notNull().default("#0E9384"),
    patientReferencePrefix: varchar("patient_reference_prefix", { length: 12 }).notNull().default("PAT"),
    nextPatientSerial: integer("next_patient_serial").notNull().default(1),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("organizations_slug_uidx").on(table.slug),
    check("organizations_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
    check("organizations_patient_reference_prefix_ck", sql`${table.patientReferencePrefix} ~ '^[A-Z][A-Z0-9]{1,11}$'`),
    check("organizations_next_patient_serial_ck", sql`${table.nextPatientSerial} > 0`),
  ],
);

export const organizationBrandAssets = pgTable(
  "organization_brand_assets",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }),
    content: encryptedBytes("content").notNull(),
    mimeType: text("mime_type").notNull(),
    byteSize: integer("byte_size").notNull(),
    sha256: varchar("sha256", { length: 64 }).notNull(),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("organization_brand_assets_org_uidx").on(table.organizationId),
    check("organization_brand_assets_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
    check("organization_brand_assets_size_ck", sql`${table.byteSize} > 0 AND ${table.byteSize} <= 2097152`),
    check("organization_brand_assets_mime_ck", sql`${table.mimeType} IN ('image/png', 'image/jpeg', 'image/webp')`),
  ],
);

export const scoringConnections = pgTable(
  "scoring_connections",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    deploymentId: entityId("deployment_id").notNull(),
    scoringOrganizationId: entityId("scoring_organization_id").notNull(),
    encryptedCredential: encryptedBytes("encrypted_credential").notNull(),
    credentialIv: encryptedBytes("credential_iv").notNull(),
    keyVersion: text("key_version").notNull(),
    activatedAt: timestamp("activated_at", { withTimezone: true }).notNull().defaultNow(),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("scoring_connections_organization_uidx").on(table.organizationId),
    check("scoring_connections_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
    check("scoring_connections_deployment_id_ulid_ck", sql`${table.deploymentId} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
    check("scoring_connections_scoring_org_id_ulid_ck", sql`${table.scoringOrganizationId} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const facilities = pgTable(
  "facilities",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    name: text("name").notNull(),
    code: text("code").notNull(),
    timezone: text("timezone").notNull().default("Asia/Kolkata"),
    status: facilityStatus("status").notNull().default("ACTIVE"),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("facilities_org_id_uidx").on(table.organizationId, table.id),
    uniqueIndex("facilities_org_code_uidx").on(table.organizationId, table.code),
    index("facilities_org_idx").on(table.organizationId),
    check("facilities_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const users = pgTable(
  "users",
  {
    id: entityId("id").primaryKey(),
    email: text("email").notNull(),
    displayName: text("display_name").notNull(),
    passwordHash: text("password_hash"),
    platformRole: platformRole("platform_role").notNull().default("USER"),
    mfaEnabled: boolean("mfa_enabled").notNull().default(false),
    status: userStatus("status").notNull().default("INVITED"),
    lastSignedInAt: timestamp("last_signed_in_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("users_email_uidx").on(table.email),
    check("users_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const organizationMemberships = pgTable(
  "organization_memberships",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    userId: entityId("user_id").notNull().references(() => users.id),
    role: membershipRole("role").notNull().default("MEDICAL"),
    isActive: boolean("is_active").notNull().default(true),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("organization_memberships_org_id_uidx").on(table.organizationId, table.id),
    uniqueIndex("organization_memberships_org_id_user_uidx").on(table.organizationId, table.id, table.userId),
    uniqueIndex("organization_memberships_org_user_uidx").on(table.organizationId, table.userId),
    index("organization_memberships_user_idx").on(table.userId),
    check("organization_memberships_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const facilityMemberships = pgTable(
  "facility_memberships",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    organizationMembershipId: entityId("organization_membership_id").notNull(),
    facilityId: entityId("facility_id").notNull(),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("facility_memberships_membership_facility_uidx").on(table.organizationMembershipId, table.facilityId),
    foreignKey({
      name: "facility_memberships_org_membership_fk",
      columns: [table.organizationId, table.organizationMembershipId],
      foreignColumns: [organizationMemberships.organizationId, organizationMemberships.id],
    }),
    foreignKey({
      name: "facility_memberships_org_facility_fk",
      columns: [table.organizationId, table.facilityId],
      foreignColumns: [facilities.organizationId, facilities.id],
    }),
    check("facility_memberships_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const invitations = pgTable(
  "invitations",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    email: text("email").notNull(),
    role: membershipRole("role").notNull().default("MEDICAL"),
    platformRole: platformRole("platform_role").notNull().default("USER"),
    tokenHash: text("token_hash").notNull(),
    status: invitationStatus("status").notNull().default("PENDING"),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    invitedByMembershipId: entityId("invited_by_membership_id"),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("invitations_token_hash_uidx").on(table.tokenHash),
    uniqueIndex("invitations_org_id_uidx").on(table.organizationId, table.id),
    uniqueIndex("invitations_pending_org_email_uidx")
      .on(table.organizationId, sql`lower(${table.email})`)
      .where(sql`${table.status} = 'PENDING'`),
    index("invitations_org_status_idx").on(table.organizationId, table.status),
    foreignKey({
      name: "invitations_org_inviter_fk",
      columns: [table.organizationId, table.invitedByMembershipId],
      foreignColumns: [organizationMemberships.organizationId, organizationMemberships.id],
    }),
    check("invitations_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const invitationFacilities = pgTable(
  "invitation_facilities",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    invitationId: entityId("invitation_id").notNull(),
    facilityId: entityId("facility_id").notNull(),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("invitation_facilities_invitation_facility_uidx").on(table.invitationId, table.facilityId),
    foreignKey({
      name: "invitation_facilities_org_invitation_fk",
      columns: [table.organizationId, table.invitationId],
      foreignColumns: [invitations.organizationId, invitations.id],
    }),
    foreignKey({
      name: "invitation_facilities_org_facility_fk",
      columns: [table.organizationId, table.facilityId],
      foreignColumns: [facilities.organizationId, facilities.id],
    }),
    check("invitation_facilities_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const authSessions = pgTable(
  "auth_sessions",
  {
    id: entityId("id").primaryKey(),
    userId: entityId("user_id").notNull().references(() => users.id),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    membershipId: entityId("membership_id").notNull(),
    tokenHash: text("token_hash").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("auth_sessions_token_hash_uidx").on(table.tokenHash),
    index("auth_sessions_user_idx").on(table.userId),
    index("auth_sessions_expiry_idx").on(table.expiresAt),
    foreignKey({ name: "auth_sessions_org_membership_user_fk", columns: [table.organizationId, table.membershipId, table.userId], foreignColumns: [organizationMemberships.organizationId, organizationMemberships.id, organizationMemberships.userId] }),
    check("auth_sessions_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const mfaChallenges = pgTable(
  "mfa_challenges",
  {
    id: entityId("id").primaryKey(),
    userId: entityId("user_id").notNull().references(() => users.id),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    membershipId: entityId("membership_id").notNull(),
    challengeTokenHash: text("challenge_token_hash").notNull(),
    otpHash: text("otp_hash").notNull(),
    attempts: integer("attempts").notNull().default(0),
    maxAttempts: integer("max_attempts").notNull().default(5),
    resendCount: integer("resend_count").notNull().default(0),
    lastSentAt: timestamp("last_sent_at", { withTimezone: true }).notNull().defaultNow(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    consumedAt: timestamp("consumed_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("mfa_challenges_token_hash_uidx").on(table.challengeTokenHash),
    index("mfa_challenges_user_idx").on(table.userId),
    foreignKey({ name: "mfa_challenges_org_membership_user_fk", columns: [table.organizationId, table.membershipId, table.userId], foreignColumns: [organizationMemberships.organizationId, organizationMemberships.id, organizationMemberships.userId] }),
    check("mfa_challenges_attempts_ck", sql`${table.attempts} >= 0 AND ${table.maxAttempts} >= 1 AND ${table.resendCount} >= 0`),
    check("mfa_challenges_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const authenticationFailures = pgTable(
  "authentication_failures",
  {
    principalHash: varchar("principal_hash", { length: 64 }).primaryKey(),
    failedAttempts: integer("failed_attempts").notNull().default(0),
    windowStartedAt: timestamp("window_started_at", { withTimezone: true }).notNull().defaultNow(),
    lockedUntil: timestamp("locked_until", { withTimezone: true }),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [check("authentication_failures_count_ck", sql`${table.failedAttempts} >= 0`)],
);

export const organizationEntitlements = pgTable(
  "organization_entitlements",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    userLimit: integer("user_limit"),
    effectiveFrom: timestamp("effective_from", { withTimezone: true }).notNull().defaultNow(),
    effectiveUntil: timestamp("effective_until", { withTimezone: true }),
    changedByMembershipId: entityId("changed_by_membership_id"),
    reason: text("reason").notNull(),
    ...timestamps,
  },
  (table) => [
    index("organization_entitlements_org_effective_idx").on(table.organizationId, table.effectiveFrom),
    foreignKey({
      name: "organization_entitlements_org_changer_fk",
      columns: [table.organizationId, table.changedByMembershipId],
      foreignColumns: [organizationMemberships.organizationId, organizationMemberships.id],
    }),
    check("organization_entitlements_user_limit_ck", sql`${table.userLimit} IS NULL OR ${table.userLimit} >= 0`),
    check("organization_entitlements_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const patients = pgTable(
  "patients",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    homeFacilityId: entityId("home_facility_id"),
    encryptedExternalReference: encryptedBytes("encrypted_external_reference").notNull(),
    externalReferenceLookupHash: text("external_reference_lookup_hash").notNull(),
    referencePrefix: varchar("reference_prefix", { length: 12 }).notNull().default("PAT"),
    serialNumber: integer("serial_number").notNull().default(0),
    dateOfBirth: date("date_of_birth"),
    sex: patientSex("sex").notNull().default("UNKNOWN"),
    encryptedProfile: encryptedBytes("encrypted_profile").notNull(),
    encryptionKeyVersion: text("encryption_key_version").notNull(),
    isArchived: boolean("is_archived").notNull().default(false),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("patients_org_id_uidx").on(table.organizationId, table.id),
    uniqueIndex("patients_org_serial_uidx").on(table.organizationId, table.serialNumber),
    uniqueIndex("patients_org_external_reference_hash_uidx").on(table.organizationId, table.externalReferenceLookupHash),
    index("patients_org_facility_idx").on(table.organizationId, table.homeFacilityId),
    foreignKey({
      name: "patients_org_home_facility_fk",
      columns: [table.organizationId, table.homeFacilityId],
      foreignColumns: [facilities.organizationId, facilities.id],
    }),
    check("patients_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
    check("patients_reference_prefix_ck", sql`${table.referencePrefix} ~ '^[A-Z][A-Z0-9]{1,11}$'`),
    check("patients_serial_number_ck", sql`${table.serialNumber} > 0`),
  ],
);

export const questionnaireDefinitions = pgTable(
  "questionnaire_definitions",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").references(() => organizations.id),
    scopeKey: text("scope_key").notNull(),
    key: text("key").notNull(),
    version: text("version").notNull(),
    schema: jsonb("schema").notNull(),
    checksum: text("checksum").notNull(),
    isPublished: boolean("is_published").notNull().default(false),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("questionnaire_definitions_scope_id_uidx").on(table.scopeKey, table.id),
    uniqueIndex("questionnaire_definitions_scope_key_version_uidx").on(table.scopeKey, table.key, table.version),
    check(
      "questionnaire_definitions_scope_ck",
      sql`(${table.organizationId} IS NULL AND ${table.scopeKey} = 'GLOBAL') OR (${table.organizationId} IS NOT NULL AND ${table.scopeKey} = ${table.organizationId}::text)`,
    ),
    check("questionnaire_definitions_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const assessments = pgTable(
  "assessments",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    patientId: entityId("patient_id").notNull(),
    facilityId: entityId("facility_id"),
    questionnaireDefinitionId: entityId("questionnaire_definition_id").notNull(),
    questionnaireScopeKey: text("questionnaire_scope_key").notNull(),
    status: assessmentStatus("status").notNull().default("DRAFT"),
    assignedToMembershipId: entityId("assigned_to_membership_id"),
    createdByMembershipId: entityId("created_by_membership_id").notNull(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("assessments_org_id_uidx").on(table.organizationId, table.id),
    index("assessments_org_status_idx").on(table.organizationId, table.status),
    index("assessments_org_patient_idx").on(table.organizationId, table.patientId),
    foreignKey({
      name: "assessments_org_patient_fk",
      columns: [table.organizationId, table.patientId],
      foreignColumns: [patients.organizationId, patients.id],
    }),
    foreignKey({
      name: "assessments_org_assignee_fk",
      columns: [table.organizationId, table.assignedToMembershipId],
      foreignColumns: [organizationMemberships.organizationId, organizationMemberships.id],
    }),
    foreignKey({
      name: "assessments_org_creator_fk",
      columns: [table.organizationId, table.createdByMembershipId],
      foreignColumns: [organizationMemberships.organizationId, organizationMemberships.id],
    }),
    foreignKey({
      name: "assessments_org_facility_fk",
      columns: [table.organizationId, table.facilityId],
      foreignColumns: [facilities.organizationId, facilities.id],
    }),
    foreignKey({
      name: "assessments_questionnaire_scope_fk",
      columns: [table.questionnaireScopeKey, table.questionnaireDefinitionId],
      foreignColumns: [questionnaireDefinitions.scopeKey, questionnaireDefinitions.id],
    }),
    check(
      "assessments_questionnaire_scope_ck",
      sql`${table.questionnaireScopeKey} = 'GLOBAL' OR ${table.questionnaireScopeKey} = ${table.organizationId}::text`,
    ),
    check("assessments_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const assessmentAnswers = pgTable(
  "assessment_answers",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    assessmentId: entityId("assessment_id").notNull(),
    questionKey: text("question_key").notNull(),
    answer: jsonb("answer").notNull(),
    answeredByMembershipId: entityId("answered_by_membership_id").notNull(),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("assessment_answers_assessment_question_uidx").on(table.assessmentId, table.questionKey),
    foreignKey({
      name: "assessment_answers_org_assessment_fk",
      columns: [table.organizationId, table.assessmentId],
      foreignColumns: [assessments.organizationId, assessments.id],
    }),
    foreignKey({
      name: "assessment_answers_org_answerer_fk",
      columns: [table.organizationId, table.answeredByMembershipId],
      foreignColumns: [organizationMemberships.organizationId, organizationMemberships.id],
    }),
    check("assessment_answers_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const faceScanSessions = pgTable(
  "face_scan_sessions",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    assessmentId: entityId("assessment_id").notNull(),
    provider: text("provider").notNull(),
    providerSessionReference: text("provider_session_reference"),
    status: scanStatus("status").notNull().default("REQUESTED"),
    failureCode: text("failure_code"),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("face_scan_sessions_org_id_uidx").on(table.organizationId, table.id),
    index("face_scan_sessions_org_assessment_idx").on(table.organizationId, table.assessmentId),
    foreignKey({
      name: "face_scan_sessions_org_assessment_fk",
      columns: [table.organizationId, table.assessmentId],
      foreignColumns: [assessments.organizationId, assessments.id],
    }),
    check("face_scan_sessions_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const measurements = pgTable(
  "measurements",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    assessmentId: entityId("assessment_id").notNull(),
    faceScanSessionId: entityId("face_scan_session_id"),
    provenance: measurementProvenance("provenance").notNull(),
    values: jsonb("values").notNull(),
    capturedAt: timestamp("captured_at", { withTimezone: true }).notNull(),
    recordedByMembershipId: entityId("recorded_by_membership_id"),
    ...timestamps,
  },
  (table) => [
    index("measurements_org_assessment_idx").on(table.organizationId, table.assessmentId),
    foreignKey({
      name: "measurements_org_assessment_fk",
      columns: [table.organizationId, table.assessmentId],
      foreignColumns: [assessments.organizationId, assessments.id],
    }),
    foreignKey({
      name: "measurements_org_face_scan_fk",
      columns: [table.organizationId, table.faceScanSessionId],
      foreignColumns: [faceScanSessions.organizationId, faceScanSessions.id],
    }),
    foreignKey({
      name: "measurements_org_recorder_fk",
      columns: [table.organizationId, table.recordedByMembershipId],
      foreignColumns: [organizationMemberships.organizationId, organizationMemberships.id],
    }),
    check("measurements_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const scoringRequests = pgTable(
  "scoring_requests",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    assessmentId: entityId("assessment_id").notNull(),
    idempotencyKey: text("idempotency_key").notNull(),
    externalRequestId: text("external_request_id"),
    status: scoringRequestStatus("status").notNull().default("PENDING"),
    requestedVersion: text("requested_version"),
    failureCode: text("failure_code"),
    requestedAt: timestamp("requested_at", { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("scoring_requests_org_id_uidx").on(table.organizationId, table.id),
    uniqueIndex("scoring_requests_org_idempotency_uidx").on(table.organizationId, table.idempotencyKey),
    index("scoring_requests_org_assessment_idx").on(table.organizationId, table.assessmentId),
    foreignKey({
      name: "scoring_requests_org_assessment_fk",
      columns: [table.organizationId, table.assessmentId],
      foreignColumns: [assessments.organizationId, assessments.id],
    }),
    check("scoring_requests_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const scoringResults = pgTable(
  "scoring_results",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    assessmentId: entityId("assessment_id").notNull(),
    scoringRequestId: entityId("scoring_request_id").notNull(),
    scoringVersion: text("scoring_version").notNull(),
    ruleChecksum: text("rule_checksum").notNull(),
    result: jsonb("result").notNull(),
    calculatedAt: timestamp("calculated_at", { withTimezone: true }).notNull(),
    receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow(),
    ...timestamps,
  },
  (table) => [
    uniqueIndex("scoring_results_request_uidx").on(table.scoringRequestId),
    index("scoring_results_org_assessment_idx").on(table.organizationId, table.assessmentId),
    foreignKey({
      name: "scoring_results_org_assessment_fk",
      columns: [table.organizationId, table.assessmentId],
      foreignColumns: [assessments.organizationId, assessments.id],
    }),
    foreignKey({
      name: "scoring_results_org_request_fk",
      columns: [table.organizationId, table.scoringRequestId],
      foreignColumns: [scoringRequests.organizationId, scoringRequests.id],
    }),
    check("scoring_results_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);

export const auditEvents = pgTable(
  "audit_events",
  {
    id: entityId("id").primaryKey(),
    organizationId: entityId("organization_id").notNull().references(() => organizations.id),
    actorMembershipId: entityId("actor_membership_id"),
    assessmentId: entityId("assessment_id"),
    actorType: text("actor_type").notNull(),
    action: text("action").notNull(),
    resourceType: text("resource_type").notNull(),
    resourceId: text("resource_id"),
    requestId: text("request_id").notNull(),
    ipAddressHash: text("ip_address_hash"),
    metadata: jsonb("metadata").notNull().default({}),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("audit_events_org_occurred_idx").on(table.organizationId, table.occurredAt),
    index("audit_events_resource_idx").on(table.resourceType, table.resourceId),
    foreignKey({
      name: "audit_events_org_actor_fk",
      columns: [table.organizationId, table.actorMembershipId],
      foreignColumns: [organizationMemberships.organizationId, organizationMemberships.id],
    }),
    foreignKey({
      name: "audit_events_org_assessment_fk",
      columns: [table.organizationId, table.assessmentId],
      foreignColumns: [assessments.organizationId, assessments.id],
    }),
    check("audit_events_id_ulid_ck", sql`${table.id} ~ '^[0-9A-HJKMNP-TV-Z]{26}$'`),
  ],
);
