import {afterAll,beforeAll,describe,expect,test} from "bun:test";
import {mkdtemp,rm} from "node:fs/promises";import {tmpdir} from "node:os";import {join} from "node:path";import {createHash} from "node:crypto";
import postgres from "postgres";import {drizzle} from "drizzle-orm/postgres-js";import {eq} from "drizzle-orm";
import {loadApplicationConfig} from "@niq/application-config";import {createEntityId} from "@niq/application-domain";
import {AssessmentWorkflowService,patientAnswers} from "./assessment-workflow";import {PostgresApplicationService} from "./postgres-application";
import {encryptPatientData,patientDataKey} from "../security/patient-data";import {encryptCredential} from "../security/credential-encryption";
import type {Principal} from "./application";import * as tables from "../db/schema";
function questionnaire(){
 const spec:Record<string,string[]>={disease_status:["tumour_type:multi_select","stage:select","relapse_status:select"],treatment:["treatment_status:conditional","cancer_surgical_status:select","current_cancer_treatment:multi_select","current_medications:multi_select","supplements_intake:multi_select"],health_history:["co_morbidities:multi_select","previous_surgeries:count","family_history_cancer:yes_no"],clinical_gut_health:["appetite_status:select","gastrointestinal_symptoms:multi_select"],dietary_details:["weight_loss:calculated","dietary_symptoms:multi_select","functional_capacity:select","stress_level:select","protein_intake:derived","fluid_intake:select"]};
 const sections=Object.entries(spec).map(([id,items])=>({id,title:id,description:"",fields:items.map(item=>{const[id,type]=item.split(":") as [string,string];return{id,type,label:id,help:"",unit:"",options:["calculated","derived"].includes(type)?[]:[{id:`${id}_yes`,label:"Yes",help:""}],dependencies:[] as string[]};})}));
 const fields=sections.flatMap(s=>s.fields);
 for(const[id,values]of Object.entries({stage:["stage_metastatic"],treatment_status:["treatment_status_palliative_care"],cancer_surgical_status:["cancer_surgical_status_done","cancer_surgical_status_planned"]}))fields.find(f=>f.id===id)!.options=values.map(id=>({id,label:id,help:""}));
 for(const[id,dependencies]of Object.entries({treatment_status:["palliative_status","palliative_timing"],previous_surgeries:["previous_surgery_count"],weight_loss:["previous_weight_kg","current_weight_kg"],protein_intake:["dietary_intake"]}))fields.find(f=>f.id===id)!.dependencies=dependencies;
 return{formatVersion:2,profile:"NIQ_FINAL_ASSESSMENT",sections,supportingInputs:["palliative_status","palliative_timing","previous_surgery_count","previous_weight_kg","current_weight_kg","dietary_intake"].map(id=>({id,label:id,kind:id.includes("weight")||id.endsWith("count")?"number":"select",required:false,options:[{id:"post_treatment",label:"Post treatment",help:""}]}))};
}
test("missing birth date and contact remain missing",()=>expect(patientAnswers({id:"p",reference:"P",displayName:"Test",dateOfBirth:null as any,gender:"UNKNOWN",homeFacility:null},new Date())).toMatchObject({age:null,contact:""}));
// Must point ONLY to an isolated, migrated disposable database.
describe.skipIf(!process.env.ASSESSMENT_TEST_DATABASE_URL)("assessment PostgreSQL lifecycle",()=>{
 const client=postgres(process.env.ASSESSMENT_TEST_DATABASE_URL!,{max:10,prepare:false}),db=drizzle(client);
 const org=createEntityId(),facility=createEntityId(),other=createEntityId(),patient=createEntityId(),user=createEntityId(),membership=createEntityId();
 const actor:Principal={userId:user,membershipId:membership,organizationId:org,email:"fixture@example.test",displayName:"Fixture",role:"MEDICAL",platformRole:"USER"};const context={requestId:"test"};let service:AssessmentWorkflowService,root:string,id:string;let starts=0;const keys:string[]=[];
 beforeAll(async()=>{
 root=await mkdtemp(join(tmpdir(),"niq-workflow-"));const config=loadApplicationConfig({DATABASE_URL:process.env.ASSESSMENT_TEST_DATABASE_URL,SESSION_SECRET:"test-secret-32-characters-long-enough",SCORING_API_URL:"http://scoring.example.test",SCORING_CREDENTIAL_ENCRYPTION_KEY:Buffer.alloc(32,1).toString("base64"),REPORT_UPLOAD_ROOT:root});
 await db.insert(tables.organizations).values({id:org,legalName:"Fixture",displayName:"Fixture",slug:`fixture-${org.toLowerCase()}`});await db.insert(tables.users).values({id:user,email:`${user}@test.example`,displayName:"Fixture",status:"ACTIVE"});await db.insert(tables.organizationMemberships).values({id:membership,organizationId:org,userId:user,role:"MEDICAL"});await db.insert(tables.facilities).values([{id:facility,organizationId:org,name:"Allowed",code:"A"},{id:other,organizationId:org,name:"Hidden",code:"B"}]);await db.insert(tables.facilityMemberships).values({id:createEntityId(),organizationId:org,organizationMembershipId:membership,facilityId:facility});
 const key=patientDataKey(undefined,config.SESSION_SECRET);await db.insert(tables.patients).values({id:patient,organizationId:org,homeFacilityId:facility,encryptedExternalReference:encryptPatientData("MRN",key),externalReferenceLookupHash:patient,serialNumber:1,dateOfBirth:"1990-01-01",gender:"FEMALE",encryptedProfile:encryptPatientData(JSON.stringify({name:"Fixture Patient",phone:"1234567890"}),key),encryptionKeyVersion:"v1"});const credential=encryptCredential("mock",config.SCORING_CREDENTIAL_ENCRYPTION_KEY!);await db.insert(tables.scoringConnections).values({id:createEntityId(),organizationId:org,deploymentId:createEntityId(),scoringOrganizationId:createEntityId(),encryptedCredential:credential.ciphertext,credentialIv:credential.iv,keyVersion:"v1"});
 service=new AssessmentWorkflowService({db,config,applicationService:new PostgresApplicationService(db,config,{deliver:async()=>{}}),fetcher:async(url,init)=>{const body=JSON.parse(String(init?.body));if(String(url).endsWith("start")){starts++;expect((await db.select().from(tables.assessmentInitializations).where(eq(tables.assessmentInitializations.id,body.assessmentReference)))[0]).toBeDefined();return Response.json({assessmentReference:body.assessmentReference,bindingId:"binding",ruleVersionId:"rule",checksum:"a".repeat(64),version:"FINAL-1",questionnaire:questionnaire()});}keys.push(body.idempotencyKey);throw new Error("uncertain transport");}});
 });
 afterAll(async()=>{await client.end();if(root)await rm(root,{recursive:true,force:true});});
 test("initialization is durable and idempotent, health snapshots encrypted",async()=>{const a=await service.initialize(actor,org,{patientId:patient,requestKey:"init-request-key-12345"},context);expect(a.status).toBe("READY");id=a.assessmentId!;expect((await service.initialize(actor,org,{patientId:patient,requestKey:"init-request-key-12345"},context)).assessmentId).toBe(id);expect(starts).toBe(1);expect(JSON.stringify((await db.select().from(tables.assessments).where(eq(tables.assessments.id,id)))[0]!.workflow)).not.toContain("Fixture Patient");});
 test("roles organization and changed facility permissions are enforced",async()=>{for(const denied of [{...actor,role:"SUPPORT" as const},{...actor,platformRole:"NIQ_ADMIN" as const},{...actor,organizationId:createEntityId()}])await expect(service.read(denied,org,id)).rejects.toMatchObject({code:"FORBIDDEN"});await db.update(tables.facilityMemberships).set({facilityId:other}).where(eq(tables.facilityMemberships.organizationMembershipId,membership));await expect(service.read(actor,org,id)).rejects.toMatchObject({code:"NOT_FOUND"});await db.update(tables.facilityMemberships).set({facilityId:facility}).where(eq(tables.facilityMemberships.organizationMembershipId,membership));});
 test("concurrent saves fence stale revisions and forged contact",async()=>{const outcomes=await Promise.allSettled([service.save(actor,org,id,{revision:0,answers:{height_cm:170,current_weight_kg:70,contact:"forged"}},context),service.save(actor,org,id,{revision:0,answers:{height_cm:160,current_weight_kg:65}},context)]);expect(outcomes.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect((await service.read(actor,org,id)).answers.contact).toBe("1234567890");});
 test("report digest validation successful replay and download",async()=>{let record=await service.read(actor,org,id);record=await service.reports.edit(actor,org,id,{revision:record.revision,label:"Report",purpose:"Baseline",datePrecision:"MONTH",year:2026,month:9,day:null},context);const report=record.reports[0]!,bytes=new TextEncoder().encode("%PDF-1.7\nfixture");const input={revision:record.revision,uploadKey:"upload-key-at-least-16",filename:"report.pdf",mediaType:"application/pdf" as const,size:bytes.length,sha256:createHash("sha256").update(bytes).digest("hex"),body:new Response(bytes).body!};record=await service.reports.upload(actor,org,id,report.id,input,context);expect(record.reports[0]!.files[0]!.status).toBe("READY");expect((await service.reports.upload(actor,org,id,report.id,{...input,body:new Response(bytes).body!},context)).revision).toBe(record.revision);await expect(service.reports.upload(actor,org,id,report.id,{...input,sha256:"0".repeat(64),body:new Response(bytes).body!},context)).rejects.toMatchObject({code:"CONFLICT"});const file=await service.reports.download(actor,org,id,report.id,record.reports[0]!.files[0]!.id);expect(await new Response(file.stream).text()).toContain("fixture");});
 test("pending upload blocks submission; cancellation fences late completion",async()=>{
   let record=await service.read(actor,org,id);const report=record.reports[0]!;const bytes=new TextEncoder().encode("%PDF-1.7\nlate");let controller!:ReadableStreamDefaultController<Uint8Array>;
   const body=new ReadableStream<Uint8Array>({start(c){controller=c;}});
   const pending=service.reports.upload(actor,org,id,report.id,{revision:record.revision,uploadKey:"pending-upload-key-1234",filename:"late.pdf",mediaType:"application/pdf",size:bytes.length,sha256:createHash("sha256").update(bytes).digest("hex"),body},context);
   // Observe reservation before driving the test transfer; attach rejection handler immediately.
   const outcome=pending.then(()=>"ready",()=>"cancelled");let file:typeof tables.assessmentFiles.$inferSelect|undefined;
   for(let n=0;n<100&&!file;n++){file=(await db.select().from(tables.assessmentFiles).where(eq(tables.assessmentFiles.uploadKey,"pending-upload-key-1234"))).find(f=>f.assessmentId===id);if(!file)await Bun.sleep(5);}
   expect(file?.status).toBe("PENDING");
   await expect(service.submit(actor,org,id,record.revision,context)).rejects.toMatchObject({code:"CONFLICT"});
   record=await service.reports.remove(actor,org,id,report.id,record.revision,context,file!.id);
   controller.enqueue(bytes);controller.close();expect(await outcome).toBe("cancelled");
   expect((await service.read(actor,org,id)).reports[0]!.files).toHaveLength(1);
 });
 test("uncertain scoring freezes edits and preserves retry key",async()=>{let record=await service.read(actor,org,id);record=await service.submit(actor,org,id,record.revision,context);expect(record.status).toBe("SCORING_UNAVAILABLE");await expect(service.save(actor,org,id,{revision:record.revision,answers:{}},context)).rejects.toMatchObject({code:"CONFLICT"});await service.retrySubmission(actor,org,id,context);expect(keys).toHaveLength(2);expect(new Set(keys).size).toBe(1);});
});
