import { useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { EmptyState, PageHeader } from "../components/Page";
import { StatusBadge } from "../components/StatusBadge";
import { assessments, patients } from "../lib/demo-data";
import { Icon } from "../lib/icons";

export function AssessmentsPage() {
  const [query, setQuery] = useState(""); const [tab, setTab] = useState("All");
  const visible = useMemo(()=>assessments.filter((a)=>(tab==="All" || a.status===tab) && `${a.id} ${a.patient} ${a.facility}`.toLowerCase().includes(query.toLowerCase())),[query,tab]);
  return <><PageHeader eyebrow="Clinical workflow" title="Assessments" description="Review assessment progress and scoring status." action={<Link className="btn btn-primary" to="/assessments/new"><Icon name="plus" size={18}/>Start assessment</Link>}/>
    <section className="surface queue-surface"><div className="segment-control" role="tablist" aria-label="Assessment status">{["All","Pending scoring","Under review","Completed"].map((value)=><button role="tab" aria-selected={tab===value} className={tab===value ? "active":""} onClick={()=>setTab(value)} key={value}>{value}</button>)}</div><div className="toolbar"><label className="search-control"><Icon name="search" size={18}/><span className="sr-only">Search assessments</span><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search patient, assessment or facility"/></label></div>
      <div className="assessment-list">{visible.length ? visible.map((item)=><Link className="assessment-card" to={`/assessments/${item.id}`} key={item.id}><div className="assessment-card-head"><div><span className="record-id">{item.id}</span><h2>{item.patient}</h2><p>{item.facility} · {item.date}</p></div><StatusBadge status={item.status}/></div><div className="assessment-card-foot"><span>Scoring version</span><strong>{item.version}</strong><Icon name="chevron" size={18}/></div></Link>) : <EmptyState title="No assessments found" description="Try another search or queue."/>}</div>
    </section></>;
}

export function StartAssessmentPage() {
  const [step, setStep] = useState(0); const [scanStatus, setScanStatus] = useState<"ready"|"checking"|"manual">("ready");
  const steps = ["Patient", "Measurements", "Questionnaire", "Review"];
  function tryScan(){ setScanStatus("checking"); window.setTimeout(()=>setScanStatus("manual"),700); }
  return <><PageHeader eyebrow="New assessment" title={steps[step]!} description="Draft questionnaire · not approved for clinical use"/>
    <div className="progress-surface"><div className="stepper">{steps.map((label,index)=><button key={label} className={index===step ? "active" : index<step ? "complete":""} onClick={()=>setStep(index)}><span>{index<step ? "✓" : index+1}</span><em>{label}</em></button>)}</div></div>
    <section className="surface assessment-form"><div className="draft-banner"><Icon name="alert" size={18}/><span><strong>Development questionnaire</strong> Fields and scoring may change after clinical approval.</span></div>
      {step===0 && <div className="form-content"><p className="section-kicker">Select patient</p><div className="choice-grid">{patients.map((patient,index)=><label className="choice-card" key={patient.id}><input type="radio" name="patient" defaultChecked={index===0}/><span className="choice-mark"/><span><strong>{patient.displayName}</strong><em>{patient.reference} · {patient.age} years · {patient.facility}</em></span></label>)}</div></div>}
      {step===1 && <div className="form-content"><p className="section-kicker">Automated measurement capture</p><div className="scan-card"><div className="scan-visual"><span className="face-outline">◎</span></div><div><h2>{scanStatus==="checking" ? "Checking face-scan service…" : scanStatus==="manual" ? "Face scan unavailable" : "Ready for face scan"}</h2><p>{scanStatus==="manual" ? "The service could not be reached. Required measurements are shown below automatically; the clinician does not choose the source." : "NIQ will attempt a secure face scan before showing manual fallback fields."}</p>{scanStatus==="ready" && <button className="btn btn-primary" onClick={tryScan}>Start secure scan</button>}</div></div>{scanStatus==="manual" && <div className="fallback-fields"><div className="notice notice-warning"><Icon name="alert"/><div><strong>Automated manual fallback</strong><span>Measurement provenance will be recorded automatically.</span></div></div><div className="field-grid"><label>Height (cm)<input type="number" inputMode="decimal"/></label><label>Weight (kg)<input type="number" inputMode="decimal"/></label></div></div>}</div>}
      {step===2 && <div className="form-content"><p className="section-kicker">Nutrition screening</p><div className="question-block"><h2>Has food intake reduced during the past week?</h2><p>Select the observation reported during the assessment.</p><div className="option-row"><label><input type="radio" name="intake"/><span>No change</span></label><label><input type="radio" name="intake"/><span>Some reduction</span></label><label><input type="radio" name="intake"/><span>Significant reduction</span></label></div></div><div className="question-block"><h2>Has the patient experienced unplanned weight loss?</h2><div className="option-row"><label><input type="radio" name="loss"/><span>No</span></label><label><input type="radio" name="loss"/><span>Yes</span></label><label><input type="radio" name="loss"/><span>Unknown</span></label></div></div></div>}
      {step===3 && <div className="form-content"><div className="review-hero"><span className="review-icon"><Icon name="check" size={28}/></span><h2>Ready to save</h2><p>The assessment will be saved before scoring is requested. If scoring is unavailable, it can be retried later.</p></div><dl className="definition-grid"><div><dt>Patient</dt><dd>Patient NIQ-1042</dd></div><div><dt>Facility</dt><dd>Chennai Central</dd></div><div><dt>Scoring version</dt><dd>Latest assigned draft</dd></div><div><dt>Clinical status</dt><dd>Not approved</dd></div></dl></div>}
      <div className="assessment-actions"><button className="btn btn-outline" disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))}>Back</button>{step<3 ? <button className="btn btn-primary" onClick={()=>setStep(step+1)}>Continue <Icon name="arrow" size={17}/></button> : <button className="btn btn-primary">Save and request score</button>}</div>
    </section></>;
}

export function AssessmentDetailPage() {
  const { assessmentId }=useParams(); const item=assessments.find(a=>a.id===assessmentId)??assessments[0]!;
  return <><div className="breadcrumb"><Link to="/assessments">Assessments</Link><span>/</span><span>{item.id}</span></div><PageHeader eyebrow={item.id} title={item.patient} description={`${item.facility} · ${item.date}`} action={<StatusBadge status={item.status}/>}/>
    {item.status==="Scoring unavailable" && <div className="notice notice-error"><Icon name="alert"/><div><strong>Scoring is currently unavailable</strong><span>The completed assessment is safely stored. Retry when the service is restored.</span></div><button className="btn btn-small btn-outline">Retry scoring</button></div>}
    {item.status==="Pending scoring" && <div className="notice notice-info"><Icon name="clock"/><div><strong>Waiting for a scoring result</strong><span>You can leave this page. The assessment will update when processing completes.</span></div></div>}
    <div className="detail-grid"><section className="surface"><div className="section-heading"><div><p className="page-eyebrow">Assessment data</p><h2>Recorded responses</h2></div><button className="text-button">View audit history</button></div><dl className="definition-grid"><div><dt>Questionnaire</dt><dd>Nutrition screening draft</dd></div><div><dt>Measurement source</dt><dd>Automated face scan</dd></div><div><dt>Food intake</dt><dd>Some reduction</dd></div><div><dt>Weight loss</dt><dd>Not recorded</dd></div></dl></section><aside className="surface"><div className="section-heading"><div><p className="page-eyebrow">Score record</p><h2>Traceability</h2></div></div><dl className="stacked-definition"><div><dt>Rule version</dt><dd>{item.version}</dd></div><div><dt>Clinical approval</dt><dd><span className="draft-label">Draft — not approved</span></dd></div><div><dt>Result stored</dt><dd>{item.status==="Completed"||item.status==="Under review" ? item.date : "Not yet"}</dd></div></dl></aside></div>
  </>;
}
